title: Count of Monte Cristo Translations
author: Edmundo Dantez
email: edmuundodantez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my oficial portfolio, where I'll post all of my translations,
  both in English and Portuguese, with links if applies. 
  My goal is to publicize my work in order to build confidence on my skills as 
  a translator. This will also work as a way to show my IT skills, by posting 
  my projects.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  edmuundodantez

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
